# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["test"]
  pull_request:
    branches: ["test"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with bandit
        run: |
          # stop the build if there are these bandit linting errors
          # ref: https://bandit.readthedocs.io/en/latest/plugins/index.html
          # B101 -> exec_used
          # B102 -> hardcoded_password_string
          # B103 -> set_bad_file_permissions
          # B110 -> try_except_pass
          # B501 -> request_with_no_cert_validation
          # B602 -> subprocess_popen_with_shell_equals_true
          bandit -r . -s B101,B102,B103,B110,B501,B602
